[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Terran Classic
Comment=Human after all
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Terran Classic
MetacityTheme=Terran
IconTheme=Human
CursorTheme=DMZ-White
GtkColorScheme=fg_color:#101010101010,bg_color:#efefebebe7e7,text_color:#1a1a1a1a1a1a,base_color:#ffffffffffff,selected_fg_color:#1a1a1a1a1a1a,selected_bg_color:#ffffbebe6b6b,tooltip_fg_color:#000000000000,tooltip_bg_color:#f5f5f5f5b5b5
